name: etesync_fixer
description: A small background service to fix up CalDAV/CardDAV entries created from iOS.
version: 1.0.0

environment:
  sdk: ^3.1.0

platforms:
  linux:

executables:
  etesync-fixer: etesync_fixer

dev_dependencies:
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.5.0

dart_pre_commit:
  flutter-compat: false
