name: etesync_fixer
description: A small background service to fix up CalDAV/CardDAV entries created from iOS.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

platforms:
  linux:

executables:
  etesync-fixer: etesync_fixer

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  etebase: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.11.0
  riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.5.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pubspec_generator: ^4.0.0
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  rps: ^0.7.0

dart_pre_commit:
  flutter-compat: false

scripts:
  help: dart run bin/etesync_fixer.dart help
  account:
    login: dart run bin/etesync_fixer.dart --log-level=all --config=./test-config.json account login --server=https://etebase.skycoder42.de
    fingerprint: dart run bin/etesync_fixer.dart --log-level=all --config=./test-config.json account fingerprint
    logout: dart run bin/etesync_fixer.dart --log-level=all --config=./test-config.json account logout
  invitations:
    list: dart run bin/etesync_fixer.dart --log-level=all --config=./test-config.json invitations list
  sync: dart run bin/etesync_fixer.dart --log-level=all --config=./test-config.json sync
