name: Continuous integration

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/workflows/docker_weekly.yaml"
      - ".github/workflows/docker_update.yaml"

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci_base.yaml

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    permissions:
      contents: write
    with:
      buildRunner: true

  docker:
    name: Docker
    needs:
      - cd
    if: needs.cd.outputs.releaseCreated == 'true'
    uses: ./.github/workflows/docker_base.yaml
    with:
      version: ${{ needs.cd.outputs.releaseVersion }}
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
