on:
  workflow_call:
jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      unitTestPaths: ""
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.g.dart"
      integrationTestPaths: ""
