name: Docker image update

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The version to be published. Must match the branch

jobs:
  ci:
    name: CI
    if: github.ref == format('refs/tags/v{0}', inputs.version)
    uses: ./.github/workflows/ci_base.yaml

  docker:
    name: Docker
    needs:
      - ci
    if: github.ref == format('refs/tags/v{0}', inputs.version)
    uses: ./.github/workflows/docker_base.yaml
    with:
      version: ${{ inputs.version }}
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
