on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      dockerHubUsername:
        required: true
      dockerHubToken:
        required: true
jobs:
  docker:
    name: Docker
    uses: Skycoder42/dart_test_tools/.github/workflows/docker.yml@main
    with:
      imageName: skycoder42/etesync-fixer
      version: ${{ inputs.version }}
      dockerPlatforms: linux/amd64,linux/arm64,linux/arm/v7
    secrets:
      dockerHubUsername: ${{ secrets.dockerHubUsername }}
      dockerHubToken: ${{ secrets.dockerHubToken }}
